#requires -Version 5.1
# Generated by generate.py. No administrator access or execution-policy changes.
[CmdletBinding()]
param([switch]$Check, [switch]$InstallOnly, [switch]$NoBootstrap,
      [Parameter(ValueFromRemainingArguments=$true)][string[]]$AppArgs = @())
$ErrorActionPreference = 'Stop'
$App = 'dsh'
$Package = '@deepseek-ai/dsh'
$Version = '0.1.5-rc.1'
$NodeVersion = '24.21.0'
function Say([string]$Message) { Write-Host "[$App] $Message" }
function Setting([string]$Name, [int]$Default, [int]$Maximum) {
    $raw = [Environment]::GetEnvironmentVariable($Name)
    if ([string]::IsNullOrEmpty($raw)) { return $Default }
    $number = 0
    if ($raw -notmatch '^[1-9][0-9]*$' -or -not [int]::TryParse($raw, [ref]$number) -or $number -gt $Maximum) { throw "$Name must be between 1 and $Maximum." }
    return $number
}
$Retries = Setting 'LMM_RETRIES' 3 10
$ConnectTimeout = Setting 'LMM_CONNECT_TIMEOUT' 20 300
$StallTimeout = Setting 'LMM_STALL_TIMEOUT' 120 86400
$DownloadTimeout = Setting 'LMM_DOWNLOAD_TIMEOUT' 1800 86400
$CommandTimeout = Setting 'LMM_COMMAND_TIMEOUT' 1800 86400
if ($env:OS -ne 'Windows_NT') { throw "Use $App.sh on Linux/macOS." }
foreach ($dependency in @('Get-FileHash','Expand-Archive')) {
    if (-not (Get-Command $dependency -ErrorAction SilentlyContinue)) { throw "Missing PowerShell command $dependency. Install the standard PowerShell archive/security modules before retrying." }
}
$LocalRoot = $env:LOCALAPPDATA
if ([string]::IsNullOrWhiteSpace($LocalRoot)) { throw 'LOCALAPPDATA is missing; run this script in a normal user session.' }
$Prefix = if ($env:LMM_INSTALL_ROOT) { $env:LMM_INSTALL_ROOT } else { Join-Path $LocalRoot 'LmmScripts' }
$Cache = if ($env:LMM_CACHE_ROOT) { $env:LMM_CACHE_ROOT } else { Join-Path $LocalRoot 'LmmScriptsCache' }
foreach ($directory in @($Prefix,$Cache)) {
    if (-not [IO.Path]::IsPathRooted($directory) -or [IO.Path]::GetPathRoot($directory) -eq $directory) { throw 'Install/cache paths must be absolute, non-root directories.' }
    if ((Test-Path -LiteralPath $directory) -and ((Get-Item -LiteralPath $directory).Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw 'Refusing a symlink/junction install or cache root.' }
}
$Architecture = if ($env:PROCESSOR_ARCHITEW6432) { $env:PROCESSOR_ARCHITEW6432 } else { $env:PROCESSOR_ARCHITECTURE }
if ([string]::IsNullOrWhiteSpace($Architecture)) { throw 'Unable to detect processor architecture.' }
switch ($Architecture.ToUpperInvariant()) {
    'AMD64' { $Arch = 'x64'; $NodeHash = '158f7685b44de51f6c0df1d153526cbcd3e1bc739a8dfc607721cef75de9e541' }
    'ARM64' { $Arch = 'arm64'; $NodeHash = '8779b1bde1d39f8d420e3b57aa657b39891af434d3de44a919044cec06785921' }
    default { throw "Unsupported architecture $Architecture. Install a compatible client manually." }
}
function CompatibleNode([string]$Executable) {
    if (-not $Executable -or -not (Test-Path -LiteralPath $Executable)) { return $false }
    & $Executable -e 'const [a,b]=process.versions.node.split(".").map(Number);process.exit(a>=24||(a===22&&b>=19)?0:1)' 2>$null
    return $LASTEXITCODE -eq 0
}
$NodeCommand = Get-Command node.exe -ErrorAction SilentlyContinue
$Node = if ($NodeCommand) { $NodeCommand.Source } else { $null }
$NpmCommand = Get-Command npm.cmd -ErrorAction SilentlyContinue
$NpmCli = if ($NpmCommand) { Join-Path (Split-Path $NpmCommand.Source) 'node_modules\npm\bin\npm-cli.js' } else { $null }
$Runtime = Join-Path $Prefix "node-v$NodeVersion-win-$Arch"
if (-not (CompatibleNode $Node) -or -not $NpmCli -or -not (Test-Path -LiteralPath $NpmCli)) {
    $Node = Join-Path $Runtime 'node.exe'
    $NpmCli = Join-Path $Runtime 'node_modules\npm\bin\npm-cli.js'
}
if ($Check) {
    Say "Windows/$Arch; Node >=22.19 (22.x) or >=24 and npm required."
    if (-not (CompatibleNode $Node) -or -not (Test-Path -LiteralPath $NpmCli)) { Say 'Node/npm missing; a normal run bootstraps verified Node 24.'; exit 2 }
    if (-not (Get-Command $App -ErrorAction SilentlyContinue)) { Say "$App missing; a normal run installs $Package@$Version."; exit 2 }
    Say 'Required dependencies are present.'
    exit 0
}
function Matches([string]$Path, [string]$Hash) {
    return (Test-Path -LiteralPath $Path -PathType Leaf) -and ((Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() -eq $Hash)
}
function New-DownloadRequest([Uri]$Uri) { return [Net.HttpWebRequest]::Create($Uri) }
function Download([Uri]$Uri, [string]$Destination, [string]$Hash) {
    if ($Uri.Scheme -ne 'https' -or $Uri.UserInfo) { throw 'Download URL must use HTTPS without embedded credentials.' }
    if (Matches $Destination $Hash) { Say 'Using verified cached Node archive.'; return }
    $partial = "$Destination.part"
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
    for ($attempt=1; $attempt -le $Retries; $attempt++) {
        if (Matches $partial $Hash) { Move-Item -LiteralPath $partial -Destination $Destination -Force; return }
        $response=$null; $source=$null; $output=$null
        try {
            Say "Downloading Node: attempt $attempt/$Retries. Partial downloads are retained."
            $offset = if (Test-Path -LiteralPath $partial) { (Get-Item -LiteralPath $partial).Length } else { 0L }
            $request = New-DownloadRequest $Uri
            $request.Timeout = $ConnectTimeout * 1000
            $request.ReadWriteTimeout = $StallTimeout * 1000
            $request.UserAgent = 'LMM-installer/1'
            if ($offset -gt 0) { $request.AddRange($offset) }
            $proxyValue = if ($env:HTTPS_PROXY) { $env:HTTPS_PROXY } else { $env:HTTP_PROXY }
            if ($proxyValue) {
                $proxyUri = [Uri]$proxyValue
                if ($proxyUri.Scheme -notin @('http','https')) { throw 'Use an HTTP(S) proxy with Windows PowerShell; SOCKS needs a local HTTP proxy adapter.' }
                $proxy = New-Object Net.WebProxy($proxyUri.GetLeftPart([UriPartial]::Authority))
                if ($proxyUri.UserInfo) {
                    $parts=$proxyUri.UserInfo.Split(':',2)
                    $password=if ($parts.Length -eq 2) { [Uri]::UnescapeDataString($parts[1]) } else { '' }
                    $proxy.Credentials=New-Object Net.NetworkCredential([Uri]::UnescapeDataString($parts[0]),$password)
                }
                if ($env:NO_PROXY) {
                    $proxy.BypassList=@($env:NO_PROXY.Split(',') | ForEach-Object { $hostName=$_.Trim().TrimStart('.'); if($hostName -eq '*') { '.*' } elseif($hostName) { '^https?://([^/]+\.)?' + [regex]::Escape($hostName) + '(:[0-9]+)?(/|$)' } })
                }
                $request.Proxy=$proxy
            }
            $response=$request.GetResponse()
            if ($offset -gt 0 -and [int]$response.StatusCode -eq 206) {
                if ($response.Headers['Content-Range'] -notlike "bytes $offset-*") { throw 'Invalid resume response.' }
                $mode=[IO.FileMode]::Append
            } else { $offset=0L; $mode=[IO.FileMode]::Create }
            $source=$response.GetResponseStream()
            $output=New-Object IO.FileStream($partial,$mode,[IO.FileAccess]::Write,[IO.FileShare]::None)
            $buffer=New-Object byte[] 65536
            $watch=[Diagnostics.Stopwatch]::StartNew(); $received=0L; $last=0.0
            $total=if($response.ContentLength -gt 0) { $offset+$response.ContentLength } else { 0L }
            while ($true) {
                $remaining=$DownloadTimeout-$watch.Elapsed.TotalSeconds
                if ($remaining -le 0) { throw 'Download total timeout exceeded.' }
                if ($source.CanTimeout) { $source.ReadTimeout=[int]([Math]::Min($StallTimeout,$remaining)*1000) }
                $count=$source.Read($buffer,0,$buffer.Length)
                if ($count -eq 0) { break }
                $output.Write($buffer,0,$count); $received+=$count
                if ($watch.Elapsed.TotalSeconds-$last -ge 1) {
                    $rate=$received/[Math]::Max(1,$watch.Elapsed.TotalSeconds)/1024
                    $percent=if($total -gt 0) { [Math]::Min(100,[int](100*($offset+$received)/$total)) } else { -1 }
                    Write-Progress -Activity 'Downloading Node.js' -Status ('{0:N0} KiB received, {1:N1} KiB/s' -f (($offset+$received)/1024),$rate) -PercentComplete $percent
                    $last=$watch.Elapsed.TotalSeconds
                }
            }
            $output.Dispose(); $output=$null; $source.Dispose(); $source=$null; $response.Close(); $response=$null
            if (Matches $partial $Hash) { Move-Item -LiteralPath $partial -Destination $Destination -Force; Write-Progress -Activity 'Downloading Node.js' -Completed; return }
            Remove-Item -LiteralPath $partial -Force
            Say 'Checksum mismatch; corrupted download discarded.'
        } catch {
            # Never echo proxy credentials or a raw network exception URL.
            if ($_.Exception.Response -and [int]$_.Exception.Response.StatusCode -eq 416) { Remove-Item -LiteralPath $partial -Force -ErrorAction SilentlyContinue }
            Say 'Download interrupted or failed. Check connectivity, certificate trust, proxy settings, and timeout limits.'
        } finally {
            if($output){$output.Dispose()}; if($source){$source.Dispose()}; if($response){$response.Close()}
        }
        if($attempt -lt $Retries){Start-Sleep -Seconds ($attempt*2)}
    }
    throw 'Unable to obtain a verified Node archive. Rerun to resume, or increase LMM_DOWNLOAD_TIMEOUT.'
}
function QuoteArgument([string]$Value) {
    if($Value -notmatch '[\s"]' -and $Value.Length){return $Value}
    return '"' + [regex]::Replace([regex]::Replace($Value,'(\\*)"','$1$1\"'),'(\\+)$','$1$1') + '"'
}
function Bounded([string]$Executable,[string[]]$Arguments) {
    $info=New-Object Diagnostics.ProcessStartInfo
    $info.FileName=$Executable; $info.UseShellExecute=$false
    $info.Arguments=($Arguments | ForEach-Object { QuoteArgument $_ }) -join ' '
    $process=New-Object Diagnostics.Process; $process.StartInfo=$info
    if(-not $process.Start()){throw 'Could not start the installation process.'}
    $watch=[Diagnostics.Stopwatch]::StartNew(); $last=0
    while(-not $process.WaitForExit(1000)) {
        if($watch.Elapsed.TotalSeconds -gt $CommandTimeout){
            $killer=Join-Path $env:SystemRoot 'System32\taskkill.exe'
            if(Test-Path -LiteralPath $killer){ & $killer /PID $process.Id /T /F | Out-Null }
            else { $process.Kill() }
            $process.WaitForExit(); throw 'Operation timed out. Increase LMM_COMMAND_TIMEOUT for slow networks and rerun.'
        }
        if($watch.Elapsed.TotalSeconds-$last -ge 15){Say ('Still working: {0:N0}s elapsed.' -f $watch.Elapsed.TotalSeconds);$last=$watch.Elapsed.TotalSeconds}
    }
    $code=$process.ExitCode; $process.Dispose()
    if($code -ne 0){throw "Installation command failed with exit code $code. Previous installations were not replaced."}
}
$Stage=$null; $Lock=$null
try {
    New-Item -ItemType Directory -Force -Path $Prefix,$Cache | Out-Null
    $LockPath=Join-Path $Prefix '.installer-lock'
    try { $Lock=[IO.File]::Open($LockPath,[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None) }
    catch { throw 'Another installer holds the installation lock; wait for it to finish.' }
    if(-not (CompatibleNode $Node) -or -not (Test-Path -LiteralPath $NpmCli)){
        if($NoBootstrap){throw 'Node/npm missing. Install Node 24 LTS or allow bootstrapping.'}
        $Archive="node-v$NodeVersion-win-$Arch.zip"
        $Base=if($env:LMM_NODE_BASE_URL){$env:LMM_NODE_BASE_URL.TrimEnd('/')}else{'https://nodejs.org/dist'}
        $Zip=Join-Path $Cache $Archive
        Download ([Uri]"$Base/v$NodeVersion/$Archive") $Zip $NodeHash
        if(Test-Path -LiteralPath $Runtime){throw "Incomplete runtime at $Runtime; inspect it before retrying."}
        $Stage=Join-Path $Prefix ('.stage.node.'+[Guid]::NewGuid().ToString('N'))
        Expand-Archive -LiteralPath $Zip -DestinationPath $Stage
        $Expanded=Join-Path $Stage "node-v$NodeVersion-win-$Arch"
        if(-not (CompatibleNode (Join-Path $Expanded 'node.exe'))){throw 'Downloaded Node cannot run on this Windows version.'}
        Move-Item -LiteralPath $Expanded -Destination $Runtime
        Remove-Item -LiteralPath $Stage -Recurse -Force; $Stage=$null
    }
    $env:PATH=(Split-Path $Node)+[IO.Path]::PathSeparator+$env:PATH
    $env:npm_config_fetch_retries=[string]$Retries
    $env:npm_config_fetch_retry_mintimeout='2000'
    $env:npm_config_fetch_retry_maxtimeout='30000'
    $env:npm_config_fetch_timeout=[string]($StallTimeout*1000)
    $env:npm_config_strict_ssl='true';$env:npm_config_audit='false';$env:npm_config_fund='false'
    if($env:LMM_NPM_REGISTRY){$registry=[Uri]$env:LMM_NPM_REGISTRY;if($registry.Scheme -ne 'https' -or $registry.UserInfo){throw 'Registry must use HTTPS without credentials.'};$env:npm_config_registry=$env:LMM_NPM_REGISTRY}
    $AppRoot=Join-Path $Prefix "apps\$App-$Version"
    $Entry=if($App -eq 'pi'){'node_modules\@earendil-works\pi-coding-agent\dist\bundle\cli.js'}else{'node_modules\@deepseek-ai\dsh\lib\bin.js'}
    $Client=Join-Path $AppRoot $Entry
    if(-not (Test-Path -LiteralPath $Client)){
        if($NoBootstrap){throw "$App is not installed in the managed user directory. Allow bootstrapping."}
        if(Test-Path -LiteralPath $AppRoot){throw "Incomplete installation at $AppRoot; inspect it before retrying."}
        $Stage=Join-Path $Prefix ('.stage.'+$App+'.'+[Guid]::NewGuid().ToString('N'))
        New-Item -ItemType Directory -Path $Stage -Force | Out-Null
        Say "Installing $Package@$Version into your user directory; system installations are untouched."
        Bounded $Node @($NpmCli,'install','--prefix',$Stage,'--ignore-scripts','--no-audit','--no-fund',"$Package@$Version")
        Bounded $Node @((Join-Path $Stage $Entry),'--version')
        New-Item -ItemType Directory -Force -Path (Split-Path $AppRoot) | Out-Null
        Move-Item -LiteralPath $Stage -Destination $AppRoot; $Stage=$null
    }
    $Bin=Join-Path $Prefix 'bin';New-Item -ItemType Directory -Force -Path $Bin | Out-Null
    $Launcher=Join-Path $Bin "$App.cmd"
    $NodeEscaped=$Node.Replace('%','%%');$ClientEscaped=$Client.Replace('%','%%')
    [IO.File]::WriteAllText($Launcher,"@echo off`r`n`"$NodeEscaped`" `"$ClientEscaped`" %*`r`nexit /b %errorlevel%`r`n",[Text.Encoding]::Default)
    Say "Future command: $Launcher"
    if($App -eq 'pi'){
        Bounded $Node @($Client,'install','npm:@tokennotincluded/pi-lmm-provider@0.1.0-alpha.1')
        Say 'Provider installed. Start Pi and use /login, then /model. Installation alone does not verify OAuth or model calls.'
    } elseif(-not $InstallOnly){
        Say 'Starting DSH Web. LMM provider installation is separate.'
        $Lock.Dispose();$Lock=$null
        & $Node $Client web @AppArgs
        exit $LASTEXITCODE
    }
} catch { Write-Error $_; exit 1 }
finally {
    if($Stage -and (Test-Path -LiteralPath $Stage)){Remove-Item -LiteralPath $Stage -Recurse -Force}
    if($Lock){$Lock.Dispose()}
}
