#!/usr/bin/env bash
# Generated by generate.py. Review templates/installer.sh before editing.
lmm_install_main() {
set -euo pipefail
set +x
umask 077
APP='pi'
PACKAGE='@earendil-works/pi-coding-agent'
VERSION='0.85.1'
NODE_VERSION='24.21.0'
check_only=0
install_only=0
bootstrap=1
while (($#)); do
  case "$1" in
    --help|-h)
      printf 'Usage: %s.sh [--check] [--install-only] [--no-bootstrap] [-- app arguments]\n' "$APP"
      printf 'Installs missing Node/npm and %s into a private user directory; never uses sudo.\n' "$APP"
      printf 'Network: HTTPS_PROXY/HTTP_PROXY/NO_PROXY; LMM_RETRIES, LMM_DOWNLOAD_TIMEOUT, LMM_STALL_TIMEOUT, LMM_COMMAND_TIMEOUT.\n'
      exit 0 ;;
    --check) check_only=1 ;;
    --install-only) install_only=1 ;;
    --no-bootstrap) bootstrap=0 ;;
    --) shift; break ;;
    *) printf 'Unknown installer option: %s (use -- before application arguments)\n' "$1" >&2; exit 2 ;;
  esac
  shift
done
say() { printf '[%s] %s\n' "$APP" "$*" >&2; }
fail() { say "$*"; exit 1; }
for utility in uname mkdir mktemp rm rmdir mv chmod sleep tar gzip; do
  command -v "$utility" >/dev/null 2>&1 || fail "Missing dependency: $utility. Install it with your OS package manager, then rerun."
done
: "${HOME:?HOME must identify your user directory}"
prefix=${LMM_INSTALL_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/lmm-scripts}
cache=${LMM_CACHE_ROOT:-${XDG_CACHE_HOME:-$HOME/.cache}/lmm-scripts}
[[ $prefix == /* && $cache == /* && $prefix != / && $cache != / ]] || fail 'Install/cache directories must be absolute, non-root paths.'
[[ ! -L $prefix && ! -L $cache ]] || fail 'Refusing a symlink at the install/cache root.'
retries=${LMM_RETRIES:-3}
connect_timeout=${LMM_CONNECT_TIMEOUT:-20}
stall_timeout=${LMM_STALL_TIMEOUT:-120}
download_timeout=${LMM_DOWNLOAD_TIMEOUT:-1800}
command_timeout=${LMM_COMMAND_TIMEOUT:-1800}
for value in "$retries" "$connect_timeout" "$stall_timeout" "$download_timeout" "$command_timeout"; do
  [[ $value =~ ^[1-9][0-9]*$ && ${#value} -le 5 ]] || fail 'Timeouts and retry counts must be positive integers.'
done
((retries <= 10 && connect_timeout <= 300 && stall_timeout <= 86400 && download_timeout <= 86400 && command_timeout <= 86400)) || fail 'Retry or timeout exceeds the supported limit.'
platform=$(uname -s)
arch=$(uname -m)
case "$platform" in Linux) platform=linux ;; Darwin) platform=darwin ;; *) fail "Unsupported OS: $platform. On Windows use $APP.ps1." ;; esac
case "$arch" in x86_64|amd64) arch=x64 ;; arm64|aarch64) arch=arm64 ;; *) fail "Unsupported architecture: $arch; install a compatible Node.js and client manually." ;; esac
case "$platform-$arch" in
 linux-x64) node_sha=6e1db87ef58b8819e5d5402eff1536491b18edd8eb7bee5ef7897876e88dc5ff ;;
 linux-arm64) node_sha=724282c3b43aec998aa9527380465b45d229e021b58035f5f4f63095eabfe5d5 ;;
 darwin-x64) node_sha=1462cb3b3046b815cf8ea436d3da450ec1a9f11dac7e5a46b0ada5305d7e8097 ;;
 darwin-arm64) node_sha=bed7eea5325e1108f32ce5228ddd6a5f0f08a499ee42aa7442aea583702f6057 ;;
esac
node_ok() {
  command -v node >/dev/null 2>&1 && node -e 'const [a,b]=process.versions.node.split(".").map(Number);process.exit(a>=24||(a===22&&b>=19)?0:1)' >/dev/null 2>&1 && command -v npm >/dev/null 2>&1 && npm --version >/dev/null 2>&1
}
if ((check_only)); then
  say "Platform: $platform/$arch; Node >=22.19 (22.x) or >=24 and npm required."
  node_ok || { say 'Node/npm missing or incompatible; a normal run will bootstrap verified Node 24.'; exit 2; }
  command -v "$APP" >/dev/null 2>&1 || { say "$APP is missing; a normal run will install $PACKAGE@$VERSION."; exit 2; }
  "$APP" --version
  exit 0
fi
mkdir -p "$prefix" "$cache" || fail 'Install/cache directory is not writable. Choose LMM_INSTALL_ROOT and LMM_CACHE_ROOT.'
lock="$prefix/.installer-lock"
mkdir "$lock" 2>/dev/null || fail "Another installer owns $lock. Wait for it; if interrupted, inspect it before removing the lock."
printf '%s\n' "$$" > "$lock/pid"
stage=''
cleanup() {
  [[ -z $stage || $stage != "$prefix"/.stage.* ]] || rm -rf -- "$stage"
  rm -f -- "$lock/pid"
  rmdir "$lock" 2>/dev/null || true
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
hash_matches() {
  local actual
  if command -v sha256sum >/dev/null 2>&1; then actual=$(sha256sum "$1"); actual=${actual%% *}
  elif command -v shasum >/dev/null 2>&1; then actual=$(shasum -a 256 "$1"); actual=${actual%% *}
  elif command -v openssl >/dev/null 2>&1; then actual=$(openssl dgst -sha256 "$1"); actual=${actual##* }
  else fail 'Missing SHA-256 verifier: install sha256sum, shasum, or openssl before downloading Node.'; fi
  [[ $actual == "$2" ]]
}
if ! node_ok; then
  ((bootstrap)) || fail 'Compatible Node/npm missing. Install Node 24 LTS from https://nodejs.org/ or allow bootstrapping.'
  archive="node-v$NODE_VERSION-$platform-$arch.tar.gz"
  runtime="$prefix/node-v$NODE_VERSION-$platform-$arch"
  source_url="${LMM_NODE_BASE_URL:-https://nodejs.org/dist}/v$NODE_VERSION/$archive"
  [[ $source_url == https://* && $source_url != *$'\n'* && $source_url != *'@'* ]] || fail 'Node mirror must be an HTTPS URL without credentials.'
  file="$cache/$archive"
  [[ ! -L $file && ! -L $file.part ]] || fail 'Refusing a symlink download cache entry.'
  if [[ ! -f $file ]] || ! hash_matches "$file" "$node_sha"; then
    command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1 || fail 'Missing downloader: install curl or wget. No runtime changes were made.'
    for ((attempt=1; attempt<=retries; attempt++)); do
      say "Downloading verified Node $NODE_VERSION (attempt $attempt/$retries). Progress shows actual speed; slow links may take time."
      downloaded=0
      if [[ -f $file.part ]] && hash_matches "$file.part" "$node_sha"; then mv -- "$file.part" "$file"; break; fi
      if command -v curl >/dev/null 2>&1; then
        if response_code=$(curl --write-out '%{http_code}' --fail --location --proto '=https' --proto-redir '=https' --connect-timeout "$connect_timeout" --max-time "$download_timeout" --speed-limit 128 --speed-time "$stall_timeout" --continue-at - --output "$file.part" "$source_url"); then downloaded=1
        else
          curl_status=$?
          if ((curl_status == 33 || curl_status == 36)) || [[ $response_code == 416 ]]; then
            say 'Server cannot resume this partial transfer; retrying from the beginning.'
            rm -f -- "$file.part"
          fi
        fi
      else
        command -v timeout >/dev/null 2>&1 || fail 'wget needs the timeout utility for a bounded transfer; install curl or timeout.'
        if timeout "$download_timeout" wget --https-only --continue --connect-timeout="$connect_timeout" --read-timeout="$stall_timeout" --tries=1 --output-document="$file.part" "$source_url"; then downloaded=1; fi
      fi
      if ((downloaded)) && hash_matches "$file.part" "$node_sha"; then mv -- "$file.part" "$file"; break; fi
      if ((downloaded)); then
        say 'Checksum mismatch: discarding incomplete or corrupted archive.'
        rm -f -- "$file.part"
      elif [[ -s $file.part ]]; then
        say 'Transfer interrupted. Retaining the partial file for the next attempt.'
      fi
      ((attempt == retries)) || sleep "$((attempt * 2))"
    done
    if [[ ! -f $file ]] || ! hash_matches "$file" "$node_sha"; then
      fail 'Node download failed. Check proxy/network settings, or increase LMM_DOWNLOAD_TIMEOUT; rerun to resume.'
    fi
  else say 'Using verified cached Node archive.'; fi
  if [[ ! -x $runtime/bin/node || ! -f $runtime/lib/node_modules/npm/bin/npm-cli.js ]]; then
    [[ ! -e $runtime ]] || fail "Incomplete runtime at $runtime; inspect it before retrying."
    stage=$(mktemp -d "$prefix/.stage.node.XXXXXX")
    tar -xzf "$file" -C "$stage"
    "$stage/${archive%.tar.gz}/bin/node" --version >/dev/null 2>&1 || fail 'Node cannot run on this OS/libc. On Alpine use apk-provided Node/npm; check OS compatibility.'
    mv -- "$stage/${archive%.tar.gz}" "$runtime"
    rm -rf -- "$stage"; stage=''
  fi
  export PATH="$runtime/bin:$PATH"
  node_ok || fail 'Bootstrapped Node/npm failed verification.'
fi
export npm_config_fetch_retries="$retries"
export npm_config_fetch_retry_mintimeout=2000
export npm_config_fetch_retry_maxtimeout=30000
export npm_config_fetch_timeout="$((stall_timeout * 1000))"
export npm_config_strict_ssl=true
export npm_config_audit=false
export npm_config_fund=false
if [[ -n ${LMM_NPM_REGISTRY:-} ]]; then
  [[ $LMM_NPM_REGISTRY == https://* && $LMM_NPM_REGISTRY != *'@'* ]] || fail 'Registry must use HTTPS without embedded credentials.'
  export npm_config_registry="$LMM_NPM_REGISTRY"
fi
# Node owns the child process group, so cancellation/timeouts cannot leave an
# npm child installing into a staging directory after cleanup.
bounded() {
  node - "$command_timeout" "$@" <<'JS'
const {spawn}=require('node:child_process');
const [seconds,command,...args]=process.argv.slice(2);
const child=spawn(command,args,{stdio:'inherit',detached:true});
let timedOut=false,stopping=false;
function stop(code){if(stopping)return;stopping=true;timedOut=code===124;try{process.kill(-child.pid,'SIGTERM')}catch{};const hard=setTimeout(()=>{try{process.kill(-child.pid,'SIGKILL')}catch{}},3000);hard.unref()}
const start=Date.now();const heartbeat=setInterval(()=>process.stderr.write(`[install] Still working: ${Math.floor((Date.now()-start)/1000)}s elapsed.\n`),15000);
const timeout=setTimeout(()=>{process.stderr.write('[install] Operation timed out; increase LMM_COMMAND_TIMEOUT for a slow connection.\n');stop(124)},Number(seconds)*1000);
process.on('SIGINT',()=>stop(130));process.on('SIGTERM',()=>stop(143));
child.on('error',e=>{clearInterval(heartbeat);clearTimeout(timeout);process.stderr.write(`[install] Cannot start ${command}: ${e.code}\n`);process.exitCode=1});
child.on('exit',(code,signal)=>{clearInterval(heartbeat);clearTimeout(timeout);process.exitCode=timedOut?124:signal?130:code??1});
JS
}
client=$(command -v "$APP" || true)
if [[ -n $client ]]; then
  bounded "$client" --version || fail "Existing $APP cannot start. Repair that installation or remove it from PATH before retrying."
  say "Using existing $APP; it will not be overwritten."
else
  ((bootstrap)) || fail "$APP missing; allow bootstrapping or install $PACKAGE@$VERSION manually."
  appdir="$prefix/apps/$APP-$VERSION"
  if [[ ! -x $appdir/node_modules/.bin/$APP ]]; then
    [[ ! -e $appdir ]] || fail "Incomplete installation at $appdir; inspect it before retrying."
    mkdir -p "$prefix/apps" "$prefix/bin"
    stage=$(mktemp -d "$prefix/.stage.$APP.XXXXXX")
    say "Installing $PACKAGE@$VERSION. npm retries use exponential backoff and its integrity-checked cache."
    bounded npm install --prefix "$stage" --ignore-scripts --no-audit --no-fund "$PACKAGE@$VERSION" || fail 'Client installation failed; the previous installation was not changed. Rerun to reuse the npm cache.'
    bounded "$stage/node_modules/.bin/$APP" --version || fail 'Installed client failed its startup check.'
    mv -- "$stage" "$appdir"; stage=''
  fi
  client="$appdir/node_modules/.bin/$APP"
  launcher="$prefix/bin/$APP"
  [[ ! -L $launcher ]] || fail 'Refusing to replace a symlink launcher.'
  {
    printf '#!/usr/bin/env bash\n'
    # The launcher expands PATH when it runs.
    # shellcheck disable=SC2016
    printf 'export PATH=%q:"$PATH"\n' "$(command -v node | while IFS= read -r p; do printf '%s' "${p%/*}"; done)"
    printf 'exec %q "$@"\n' "$client"
  } > "$launcher.next"
  chmod 700 "$launcher.next"; mv -- "$launcher.next" "$launcher"
  say "Client installed. Future command: $launcher"
fi
if [[ $APP == pi ]]; then
  say 'Installing the published LMM Pi provider; Git is not required.'
  bounded "$client" install 'npm:@tokennotincluded/pi-lmm-provider@0.1.0-alpha.1' || fail 'Provider install failed. Rerun safely; Node and Pi are already installed.'
  say 'Provider installed. Start Pi, run /login, choose LMM, then use /model. Installation does not prove OAuth or model calls work.'
else
  say 'DSH is ready. LMM provider installation is separate; this script does not claim an unpublished plugin is installed.'
  if ((!install_only)); then
    cleanup; trap - EXIT INT TERM
    exec "$client" web "$@"
  fi
fi

}
# The complete function and this block must arrive before anything executes.
if true; then
  lmm_install_main "$@"
fi
